/**
 * The Initiativantrag path: a Ministerialentwurf that went through
 * Begutachtung and whose Gesetzestext then came to the Nationalrat as a
 * motion of MPs instead of a Regierungsvorlage (docs/architecture.md
 * §12.10, 30.09.2026).
 *
 * WHY IT MATTERS FOR THIS PRODUCT: without it such a draft reads „bisher
 * keine Regierungsvorlage" — true, and still the wrong story. Measured
 * 30.09.2026, of the drafts whose Frist ended without any Vorlage, 11 of 49
 * (GP XXVI), 25 of 57 (XXVII) and 6 of 34 (XXVIII) are tied by their wording
 * to an Initiativantrag that was promulgated. Showing those as shelved would
 * be the blame counter the framing rule forbids, generated by a missing
 * pointer.
 *
 * WHY BY WORDING: the data has no link in either direction. A draft's stage
 * record only ever names Regierungsvorlagen (96 of 96 pointers in GP
 * XXVIII), and the Antrag does not name its draft (`docs/api-exploration.md`).
 * `scripts/corpus/meAntragJoin.ts` compares 5-word shingles of both
 * Gesetzestexte, calibrated against documented draft → Vorlage pairs and
 * shifted false pairs (0 of 482 false pairs reach its threshold); only its
 * „belegt" step (≥ 0,6 of the shorter text in the longer) is in the table.
 *
 * TWO CLAIMS, SEPARATED BY `carriesDraft`:
 *  - most of the DRAFT stands in the Antrag (`draftShare` ≥ 0,5): the draft
 *    took the Antrag route — the station is the Bundesgesetzblatt, and the
 *    spine and the list say so;
 *  - otherwise only a part of it did (XXVIII/6/ME: the Antrag's 570 words
 *    sit to 77 % in the draft's 11.934). Then the page names the Antrag as a
 *    sentence and the station stays where the stage record put it — under-
 *    claiming is the safe direction.
 * The 0,5 sits in a gap of the measured values (0,36 → 0,58 over the 42
 * rows), not on a round number chosen in advance.
 *
 * Pure module: no Nuxt auto-imports, so server, app and vitest read the same
 * table.
 */
import type { AntragPath } from '../types'
import { ANTRAG_PATHS } from './antragPathTable'

/** From this share of the draft's own Gesetzestext on, the draft took the Antrag route. */
export const CARRIES_DRAFT_SHARE = 0.5

/** The path for one draft, or null where the table names none. */
export function antragPathFor(gp: string, inr: number): AntragPath | null {
  return ANTRAG_PATHS[gp]?.[inr] ?? null
}

/** Does the Antrag carry most of the draft — may the station move? */
export function carriesDraft(path: AntragPath | null | undefined): path is AntragPath {
  return Boolean(path && path.draftShare >= CARRIES_DRAFT_SHARE)
}

/** The Antrag's page at Parliament. */
export function antragUrl(gp: string, path: AntragPath): string {
  return `https://www.parlament.gv.at/gegenstand/${gp}/A/${path.antrag.inr}`
}

/** „81 %" — whole percent, the precision the shingle measure supports. */
export function sharePercentDe(share: number): string {
  return `${Math.round(share * 100)}\u00a0%`
}
