/**
 * GENERATED by `scripts/corpus/meAntragTable.ts` — do not edit by hand;
 * re-run it (and `corpus/meAntragJoin.ts` before it) when a period closes.
 * What the numbers mean and why this is a table: `antragPath.ts`.
 */
import type { AntragPath } from '../types'

export const ANTRAG_PATHS_MEASURED: Readonly<Record<string, string>> = {
  XXVI: '2026-09-30',
  XXVII: '2026-09-30',
  XXVIII: '2026-09-30',
}

export const ANTRAG_PATHS: Readonly<Record<string, Readonly<Record<number, AntragPath>>>> = {
  XXVI: {
    27: { antrag: { citation: '262/A', inr: 262, title: 'Alternative Investmentfonds Manager-Gesetz, Immobilien-Investmentfondsgesetz u.a., Änderung', einlangen: '2018-05-17', bgblNumber: 'Bundesgesetzblatt I Nr. 67/2018' }, draftShare: 0.25, antragShare: 0.79, duringFrist: false },
    68: { antrag: { citation: '387/A', inr: 387, title: 'STS-Verbriefungsvollzugsgesetz; Finanzmarktaufsichtsbehördengesetz, Investmentfondsgesetz u.a., Änderung', einlangen: '2018-09-26', bgblNumber: 'Bundesgesetzblatt I Nr. 76/2018' }, draftShare: 0.93, antragShare: 0.72, duringFrist: false },
    136: { antrag: { citation: '887/A', inr: 887, title: 'AWG-Rechtsbereinigungsnovelle 2019', einlangen: '2019-06-12', bgblNumber: 'Bundesgesetzblatt I Nr. 71/2019' }, draftShare: 0.72, antragShare: 0.78, duringFrist: false },
    140: { antrag: { citation: '907/A', inr: 907, title: 'Wohnungsgemeinnützigkeitsgesetz – WGG, Änderung', einlangen: '2019-06-12', bgblNumber: 'Bundesgesetzblatt I Nr. 85/2019' }, draftShare: 0.78, antragShare: 0.68, duringFrist: false },
    130: { antrag: { citation: '910/A', inr: 910, title: 'Aktienrechts-Änderungsgesetz 2019 – AktRÄG 2019', einlangen: '2019-06-12', bgblNumber: 'Bundesgesetzblatt I Nr. 63/2019' }, draftShare: 0.87, antragShare: 0.79, duringFrist: false },
    146: { antrag: { citation: '872/A', inr: 872, title: 'Schulorganisationsgesetz, Schulunterrichtsgesetz u.a., Änderung', einlangen: '2019-06-12', bgblNumber: 'Bundesgesetzblatt I Nr. 86/2019' }, draftShare: 0.1, antragShare: 0.86, duringFrist: false },
    138: { antrag: { citation: '871/A', inr: 871, title: 'Bildungsinvestitionsgesetz, Änderung', einlangen: '2019-06-12', bgblNumber: 'Bundesgesetzblatt I Nr. 87/2019' }, draftShare: 0.98, antragShare: 0.97, duringFrist: false },
    147: { antrag: { citation: '984/A', inr: 984, title: 'Steuerreformgesetz 2020 – StRefG 2020', einlangen: '2019-07-03', bgblNumber: 'Bundesgesetzblatt I Nr. 103/2019' }, draftShare: 0.58, antragShare: 0.77, duringFrist: false },
    132: { antrag: { citation: '983/A', inr: 983, title: 'Abgabenänderungsgesetz 2020 – AbgÄG 2020', einlangen: '2019-07-03', bgblNumber: 'Bundesgesetzblatt I Nr. 91/2019' }, draftShare: 0.96, antragShare: 0.38, duringFrist: false },
    135: { antrag: { citation: '985/A', inr: 985, title: 'Finanz-Organisationsreformgesetz – FORG', einlangen: '2019-07-03', bgblNumber: 'Bundesgesetzblatt I Nr. 104/2019' }, draftShare: 0.88, antragShare: 0.62, duringFrist: false },
    159: { antrag: { citation: '970/A', inr: 970, title: 'Gewaltschutzgesetz 2019', einlangen: '2019-07-03', bgblNumber: 'Bundesgesetzblatt I Nr. 105/2019' }, draftShare: 0.97, antragShare: 0.02, duringFrist: false },
  },
  XXVII: {
    69: { antrag: { citation: '1065/A', inr: 1065, title: 'Schulorganisationsgesetz, Schulunterrichtsgesetz u.a., Änderung', einlangen: '2020-11-20', bgblNumber: 'Bundesgesetzblatt I Nr. 19/2021' }, draftShare: 0.81, antragShare: 0.8, duringFrist: false },
    87: { antrag: { citation: '1289/A', inr: 1289, title: 'Bauarbeiter-Urlaubs- und Abfertigungsgesetz, Bauarbeiter-Schlechtwetterentschädigungsgesetz u.a., Änderung', einlangen: '2021-02-24', bgblNumber: 'Bundesgesetzblatt I Nr. 71/2021' }, draftShare: 0.95, antragShare: 0.94, duringFrist: false },
    94: { antrag: { citation: '1301/A', inr: 1301, title: 'Arbeitsvertragsrechts-Anpassungsgesetz, Arbeitsverfassungsgesetz u.a., Änderung', einlangen: '2021-02-24', bgblNumber: 'Bundesgesetzblatt I Nr. 61/2021' }, draftShare: 0.36, antragShare: 0.62, duringFrist: false },
    164: { antrag: { citation: '2173/A', inr: 2173, title: 'COVID-19-Impfpflichtgesetz – COVID-19-IG', einlangen: '2021-12-16', bgblNumber: 'Bundesgesetzblatt I Nr. 4/2022' }, draftShare: 1, antragShare: 1, duringFrist: true },
    173: { antrag: { citation: '2224/A', inr: 2224, title: 'Güterbeförderungsgesetz, Gelegenheitsverkehrs-Gesetz u.a., Änderung', einlangen: '2022-01-20', bgblNumber: 'Bundesgesetzblatt I Nr. 18/2022' }, draftShare: 0.88, antragShare: 0.86, duringFrist: false },
    198: { antrag: { citation: '2586/A', inr: 2586, title: 'Tierschutzgesetz, Tiertransportgesetz, Änderung', einlangen: '2022-05-19', bgblNumber: 'Bundesgesetzblatt I Nr. 130/2022' }, draftShare: 1, antragShare: 0.68, duringFrist: true },
    204: { antrag: { citation: '2655/A', inr: 2655, title: 'Bundespflegegeldgesetz, Änderung', einlangen: '2022-06-15', bgblNumber: 'Bundesgesetzblatt I Nr. 129/2022' }, draftShare: 1, antragShare: 1, duringFrist: true },
    205: { antrag: { citation: '2656/A', inr: 2656, title: 'Entgelterhöhungs-Zweckzuschussgesetz – EEZG', einlangen: '2022-06-15', bgblNumber: 'Bundesgesetzblatt I Nr. 104/2022' }, draftShare: 0.99, antragShare: 0.99, duringFrist: true },
    206: { antrag: { citation: '2654/A', inr: 2654, title: 'Pflegeausbildungs-Zweckzuschussgesetz', einlangen: '2022-06-15', bgblNumber: 'Bundesgesetzblatt I Nr. 105/2022' }, draftShare: 0.99, antragShare: 0.99, duringFrist: true },
    208: { antrag: { citation: '2653/A', inr: 2653, title: 'GuKG-Novelle 2022', einlangen: '2022-06-15', bgblNumber: 'Bundesgesetzblatt I Nr. 128/2022' }, draftShare: 0.98, antragShare: 0.98, duringFrist: true },
    214: { antrag: { citation: '2893/A', inr: 2893, title: 'Gesellschaftliches Digitalisierungsgesetz 2022 – GesDigG 2022', einlangen: '2022-10-13', bgblNumber: 'Bundesgesetzblatt I Nr. 186/2022' }, draftShare: 0.96, antragShare: 0.94, duringFrist: false },
    210: { antrag: { citation: '3087/A', inr: 3087, title: 'HinweisgeberInnenschutzgesetz; Gesetz über das Bundesamt zur Korruptionsprävention und Korruptionsbekämpfung, Beamten-Dienstrechtsgesetz u.a., Änderung', einlangen: '2022-12-15', bgblNumber: 'Bundesgesetzblatt I Nr. 6/2023' }, draftShare: 0.74, antragShare: 0.7, duringFrist: false },
    233: { antrag: { citation: '3292/A', inr: 3292, title: 'Bundesgesetz über die Förderung des qualitätsvollen Journalismus in Medien des Print- und Online-Bereichs; das Presseförderungsgesetz, das KommAustria-Gesetz, Änderung', einlangen: '2023-03-30', bgblNumber: 'Bundesgesetzblatt I Nr. 163/2023' }, draftShare: 0.72, antragShare: 0.82, duringFrist: false },
    228: { antrag: { citation: '3293/A', inr: 3293, title: 'Bundesgesetz über die Wiener Zeitung GmbH und Einrichtung einer elektronischen Verlautbarungs- und Informationsplattform des Bundes – WZEVI-Gesetz', einlangen: '2023-03-30', bgblNumber: 'Bundesgesetzblatt I Nr. 46/2023' }, draftShare: 0.82, antragShare: 0.7, duringFrist: false },
    301: { antrag: { citation: '3868/A', inr: 3868, title: 'Apothekengesetz, Apothekerkammergesetz u.a, Änderung', einlangen: '2024-01-31', bgblNumber: 'Bundesgesetzblatt I Nr. 22/2024' }, draftShare: 0.88, antragShare: 0.87, duringFrist: false },
    298: { antrag: { citation: '3865/A', inr: 3865, title: 'Ärztegesetz, Änderung', einlangen: '2024-01-31', bgblNumber: 'Bundesgesetzblatt I Nr. 21/2024' }, draftShare: 0.87, antragShare: 0.85, duringFrist: false },
    311: { antrag: { citation: '3975/A', inr: 3975, title: 'Straßenverkehrsordnung 1960 (35. StVO-Novelle)', einlangen: '2024-03-21', bgblNumber: 'Bundesgesetzblatt I Nr. 52/2024' }, draftShare: 0.87, antragShare: 0.83, duringFrist: false },
    343: { antrag: { citation: '4095/A', inr: 4095, title: 'MTD-Gesetz 2024 – MTDG; Rezeptpflichtgesetz, Apothekengesetz u.a., Änderung', einlangen: '2024-06-12', bgblNumber: 'Bundesgesetzblatt I Nr. 100/2024' }, draftShare: 0.93, antragShare: 0.71, duringFrist: false },
    342: { antrag: { citation: '4132/A', inr: 4132, title: 'Sicherheitspolizeigesetz, Änderung', einlangen: '2024-06-13', bgblNumber: 'Bundesgesetzblatt I Nr. 122/2024' }, draftShare: 0.76, antragShare: 0.86, duringFrist: false },
    321: { antrag: { citation: '4119/A', inr: 4119, title: 'Bundesämtergesetz, Änderung', einlangen: '2024-06-13', bgblNumber: 'Bundesgesetzblatt I Nr. 131/2024' }, draftShare: 0.86, antragShare: 0.72, duringFrist: false },
    319: { antrag: { citation: '4124/A', inr: 4124, title: 'Berufsrechts-Änderungsgesetz 2024 – BRÄG 2024', einlangen: '2024-06-13', bgblNumber: 'Bundesgesetzblatt I Nr. 93/2024' }, draftShare: 0.75, antragShare: 0.56, duringFrist: false },
    324: { antrag: { citation: '4114/A', inr: 4114, title: 'Betriebliche Mitarbeiter- und Selbständigenvorsorgegesetz, Änderung', einlangen: '2024-06-13', bgblNumber: 'Bundesgesetzblatt I Nr. 119/2024' }, draftShare: 0.77, antragShare: 0.88, duringFrist: false },
    315: { antrag: { citation: '4117/A', inr: 4117, title: 'Tierschutzgesetz, Änderung', einlangen: '2024-06-13', bgblNumber: 'Bundesgesetzblatt I Nr. 124/2024' }, draftShare: 0.87, antragShare: 0.8, duringFrist: false },
    334: { antrag: { citation: '4113/A', inr: 4113, title: 'MiCA-Verordnung-Vollzugsgesetz; Alternative Investmentfonds Manager-Gesetz, Bankwesengesetz u.a., Änderung', einlangen: '2024-06-13', bgblNumber: 'Bundesgesetzblatt I Nr. 111/2024' }, draftShare: 0.93, antragShare: 0.92, duringFrist: false },
    320: { antrag: { citation: '4118/A', inr: 4118, title: 'EU-Qualitätsregelungen-Durchführungsgesetz, Gesundheits- und Ernährungssicherheitsgesetz, Änderung', einlangen: '2024-06-13', bgblNumber: 'Bundesgesetzblatt I Nr. 139/2024' }, draftShare: 0.72, antragShare: 0.67, duringFrist: false },
  },
  XXVIII: {
    6: { antrag: { citation: '72/A', inr: 72, title: 'Kreditdienstleister- und Kreditkäufergesetz – KKG; Bankwesengesetz, Finanzmarktaufsichtsbehördengesetz u.a., Änderung', einlangen: '2025-02-26', bgblNumber: 'Bundesgesetzblatt I Nr. 6/2025' }, draftShare: 0.03, antragShare: 0.77, duringFrist: false },
    42: { antrag: { citation: '460/A', inr: 460, title: 'Stromkosten-Ausgleichsgesetz 2025 – SAG 2025', einlangen: '2025-09-24', bgblNumber: 'Bundesgesetzblatt I Nr. 67/2025' }, draftShare: 1, antragShare: 1, duringFrist: false },
    91: { antrag: { citation: '763/A', inr: 763, title: 'Mineralölsteuergesetz, Änderung', einlangen: '2026-03-23', bgblNumber: 'Bundesgesetzblatt I Nr. 12/2026' }, draftShare: 0.84, antragShare: 0.83, duringFrist: true },
    90: { antrag: { citation: '764/A', inr: 764, title: 'Preisgesetz, Energie-Control-Gesetz, Änderung', einlangen: '2026-03-23', bgblNumber: 'Bundesgesetzblatt I Nr. 13/2026' }, draftShare: 0.99, antragShare: 0.98, duringFrist: true },
    106: { antrag: { citation: '917/A', inr: 917, title: 'Arbeitsvertragsrechts-Anpassungsgesetz, Bauarbeiter-Urlaubs- und Abfertigungsgesetz u.a., Änderung', einlangen: '2026-06-10', bgblNumber: 'Bundesgesetzblatt I Nr. 66/2026' }, draftShare: 0.84, antragShare: 0.83, duringFrist: false },
    105: { antrag: { citation: '952/A', inr: 952, title: 'Kraftfahrgesetz, Änderung (42.KFG-Novelle)', einlangen: '2026-06-11', bgblNumber: 'Bundesgesetzblatt I Nr. 79/2026' }, draftShare: 1, antragShare: 1, duringFrist: false },
  },
}
