#!/usr/bin/env vite-node
/**
 * Writes `shared/utils/antragPathTable.ts` — the Ministerialentwürfe whose
 * Gesetzestext came to the Nationalrat as an Initiativantrag and not as a
 * Regierungsvorlage (docs/architecture.md §12.10, 30.09.2026).
 *
 * Usage:   npx vite-node scripts/corpus/meAntragTable.ts [cacheDir] XXVI XXVII XXVIII
 *          (reads `<cacheDir>/<GP>-me-antrag.json` and the Gesetzestexte
 *           `corpus/meAntragJoin.ts` left in `<cacheDir>/<GP>/text/`; the
 *           default cacheDir is `.cache/begutachtung-skipped`)
 *
 * WHY A HAND-RUN TABLE and not a live join: the join reads the Gesetzestext
 * of every draft, every Antrag and every Vorlage of a period — 700 to 1.100
 * documents. No page may depend on that while somebody waits, and nothing a
 * visitor does should trigger it (`app/utils/outcomes.ts` states the rule).
 * The table moves when a period closes or a new Antrag arrives; re-run both
 * scripts then, like `rvLatency.ts` for the base rates. A draft the table
 * does not name says what it said before — „bisher keine Regierungsvorlage"
 * is the weaker claim, never a wrong one.
 *
 * WHAT GOES IN: only the hits `meAntragJoin.ts` calls „belegt" (containment
 * ≥ 0,6, read off a gap in the data, 0 of 482 shifted false pairs above
 * 0,25 over the three periods), and only for drafts WITHOUT any
 * Regierungsvorlage. A draft with a Vorlage keeps the documented chain; that
 * the same text also went as an Antrag (XXVII/171, 240, 259/ME) is a finding
 * for the docs, not for the station.
 *
 * TWO SHARES, because containment alone does not say which way round. It is
 * the share of the SHORTER text found in the longer one — 72/A (570 words)
 * sits to 77 % in 6/ME (11.934 words), while 159/ME (198 words) sits to 97 %
 * in the Gewaltschutzgesetz 2019 (12.393 words). The page has to say
 * different things about those two, so both directions are derived here from
 * containment and Jaccard on the same filtered shingles:
 *
 *   shared = C · min,  J = shared / (a + b − shared)
 *   ⇒ max / min = C · (1/J + 1) − 1,  and the larger text's share = C / that
 *
 * Which side is the shorter one is read off the word counts of the cached
 * texts.
 */
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import type { MeAntragReport } from '../lib/skippedReport'

const args = process.argv.slice(2)
const cacheDir = args[0] && !/^[IVXLC]+$/.test(args[0]) ? args.shift()! : join('.cache', 'begutachtung-skipped')
const gps = args.length ? args : ['XXVI', 'XXVII', 'XXVIII']
const OUT = join('shared', 'utils', 'antragPathTable.ts')

const words = async (file: string): Promise<number | null> => {
  try {
    return (await readFile(file, 'utf8')).split(' ').length
  } catch {
    return null
  }
}
const round2 = (x: number): number => Math.round(x * 100) / 100
/** A single-quoted TS string literal — the repo's lint style. */
const lit = (x: string): string => `'${x.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`

const blocks: string[] = []
const measured: string[] = []
for (const gp of gps) {
  const report = JSON.parse(await readFile(join(cacheDir, `${gp}-me-antrag.json`), 'utf8')) as MeAntragReport & {
    hits: (MeAntragReport['hits'][number])[]
  }
  measured.push(`  ${gp}: '${report.measuredAt}',`)
  const rows: string[] = []
  for (const h of report.hits) {
    if (!h.strong || h.meBecameRv) continue
    const wa = await words(join(cacheDir, gp, 'text', `A-${h.inr}.txt`))
    const wm = await words(join(cacheDir, gp, 'text', `ME-${h.meInr}.txt`))
    if (wa === null || wm === null) throw new Error(`${gp}: Text fehlt für ${h.citation} oder ${h.meInr}/ME — erst meAntragJoin.ts laufen lassen`)
    const ratio = h.score * (1 / h.jaccard + 1) - 1
    const larger = h.score / ratio
    const antragShorter = wa <= wm
    const antragShare = round2(antragShorter ? h.score : larger)
    const draftShare = round2(antragShorter ? larger : h.score)
    const bgbl = /^I\s+(\d+)\/(\d{4})$/.exec(h.bgbl.trim())
    if (!bgbl) throw new Error(`${gp}: unerwartete BGBl-Angabe „${h.bgbl}" bei ${h.citation}`)
    rows.push(
      `    ${h.meInr}: { antrag: { citation: ${lit(h.citation)}, inr: ${h.inr}, title: ${lit(h.title)}, ` +
      `einlangen: '${h.einlangen}', bgblNumber: 'Bundesgesetzblatt I Nr. ${bgbl[1]}/${bgbl[2]}' }, ` +
      `draftShare: ${draftShare}, antragShare: ${antragShare}, duringFrist: ${h.fristOffen} },`,
    )
  }
  blocks.push(`  ${gp}: {\n${rows.join('\n')}\n  },`)
  console.error(`${gp}: ${rows.length} Entwürfe ohne Regierungsvorlage mit belegtem Initiativantrag`)
}

await writeFile(OUT, `/**
 * GENERATED by \`scripts/corpus/meAntragTable.ts\` — do not edit by hand;
 * re-run it (and \`corpus/meAntragJoin.ts\` before it) when a period closes.
 * What the numbers mean and why this is a table: \`antragPath.ts\`.
 */
import type { AntragPath } from '../types'

export const ANTRAG_PATHS_MEASURED: Readonly<Record<string, string>> = {
${measured.join('\n')}
}

export const ANTRAG_PATHS: Readonly<Record<string, Readonly<Record<number, AntragPath>>>> = {
${blocks.join('\n')}
}
`)
console.error(`Geschrieben: ${OUT}`)
